name: Update Contents List

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "contents.html"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Script
        run: python update_contents.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add contents.html
          git diff --cached --quiet && exit 0

          git commit -m "Auto-update contents.html"
          git push
